// Offline generated artifact workflows; this does not access the user's browser session.
const {chromium}=require(process.env.NPO_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const root=path.resolve(__dirname,'..'),qa=path.resolve(process.env.NPO_QA_DIR||path.join(root,'qa')),artifact=path.join(root,'NPO结构探索器.html');
fs.mkdirSync(qa,{recursive:true});
const checks=[],errors=[];let browser,page;
const state=()=>page.evaluate(()=>NPO.getState());
const mark=s=>checks.push(s);
async function setting(key,value){await page.locator('#settings').click();await page.locator(`[data-setting="${key}"]`).selectOption(String(value));await page.locator('#settings-dialog .primary').click();}
(async()=>{
 const launch={headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']};
 if(process.env.NPO_CHROMIUM_EXECUTABLE)launch.executablePath=process.env.NPO_CHROMIUM_EXECUTABLE;
 browser=await chromium.launch(launch);page=await browser.newPage({viewport:{width:1600,height:1050}});
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.route(/^https?:/,r=>{errors.push('External request: '+r.request().url());r.abort()});
 const loadedArtifactHash=crypto.createHash('sha256').update(fs.readFileSync(artifact)).digest('hex');
 await page.goto(pathToFileURL(artifact).href);await page.waitForFunction(()=>window.NPO?.scene);
 await page.locator('[data-pricing="cost"]').click();assert.equal((await state()).total,530);
 await page.evaluate(()=>NPO.select('driver'));
 await page.locator('[data-assume="driver"]').click();await page.locator('#assumption-price').fill('5');await page.locator('#save-assumption').click();
 assert.equal((await state()).total,510);
 assert.equal(await page.evaluate(()=>{const s=NPO.getState();return NPO.computeBOM(s.config,NPO.database,s.overrides).priceFor('tia').total}),40);
 await setting('driverChannels',8);assert((await state()).staleOverrides.some(x=>x.id==='driver'));
 assert((await page.locator('#pricing-alert').innerText()).includes('暂停使用'));
 await setting('driverChannels',4);assert.equal((await state()).total,510);
 await page.reload();await page.waitForFunction(()=>window.NPO?.scene);assert.equal((await state()).total,510,'quote survives reload with bound spec');
 await page.locator('[data-assume="driver"]').click();await page.locator('#clear-assumption').click();assert.equal((await state()).total,530);
 mark('Cost inputs roll up without shifting TIA; quotes expire, restore, and persist by spec');
 // A deep quote inside a package must reserve its amount before allocating intermediate nodes.
 await page.evaluate(()=>NPO.select('els'));await page.locator('[data-assume="els"]').click();
 await page.locator('#assumption-price').fill('150');await page.locator('#save-assumption').click();assert.equal((await state()).total,455);
 await page.evaluate(()=>NPO.select('laser_die'));await page.locator('[data-assume="laser_die"]').click();
 assert((await page.locator('#detail-content').innerText()).includes('包价内'));
 await page.locator('#assumption-price').fill('10');await page.locator('#save-assumption').click();
 assert(!await page.locator('#detail-dialog').isVisible(),'valid deep quote can be saved');assert.equal((await state()).total,455);
 await page.locator('[data-assume="laser_die"]').click();await page.locator('#clear-assumption').click();
 await page.evaluate(()=>NPO.select('els'));await page.locator('[data-assume="els"]').click();await page.locator('#clear-assumption').click();
 assert.equal((await state()).total,530);mark('Deep component quote reserves space inside ancestor package without double counting');
 await page.locator('#pin-config').click();await setting('rotators',2);assert(Math.abs((await state()).total-533.6)<1e-8);
 await page.locator('#compare-config').click();assert((await page.locator('#detail-content').innerText()).includes('$3.6'));
 assert.equal(await page.locator('[data-contribution]').count(),3);
 const comparison=await page.evaluate(()=>{const s=NPO.getState(),r=NPO.compareBOM(s.comparison.config,s.comparison.overrides,s.config,s.overrides,NPO.database);return {delta:r.delta,sum:r.steps.reduce((v,s)=>v+s.amount,0)}});
 assert(Math.abs(comparison.delta-comparison.sum)<1e-8);
 await page.screenshot({path:path.join(qa,'09-comparison.png')});await page.locator('#close-detail').click();
 await page.reload();await page.waitForFunction(()=>window.NPO?.scene);assert.equal((await state()).comparison.config.rotators,1);
 assert.equal((await state()).config.rotators,2);mark('Pinned scenario is immutable, persistent, and comparison contributions reconcile');
 await page.locator('[data-pricing="allocation"]').click();assert.equal((await state()).total,530);
 await page.evaluate(()=>NPO.select('faraday'));await page.locator('#inspector [data-price="faraday"]').first().click();
 assert((await page.locator('.parameter-list').innerText()).includes('本节点权重'));
 assert((await page.locator('.parameter-list').innerText()).includes('工程假设'));await page.locator('#close-price').click();
 await page.evaluate(()=>NPO.select('fau'));assert((await page.locator('#inspector .residual-row').innerText()).includes('40.0%'));
 await page.locator('[data-expand="fau"]').click();assert.equal(await page.locator('#explode').inputValue(),'0.9');
 await page.locator('[data-expand="fau"]').click();assert.equal(await page.locator('#explode').inputValue(),'0.3');
 await page.evaluate(()=>NPO.select('tec'));assert.equal(await page.locator('.quantity-unknown').innerText(),'待确认');
 assert((await page.locator('.allocated-quantity').innerText()).includes('0.5'));mark('Parameter provenance, residual share, allocation labels, and expand actions');
 await page.evaluate(()=>NPO.select('tia'));assert.equal((await state()).signalPath,'rx');assert((await page.locator('#signal-route').innerText()).includes('接收PD'));
 await page.locator('[data-signal="tx"]').click();assert.equal((await state()).signalPath,'tx');
 await page.evaluate(()=>NPO.select('pic'));await page.waitForTimeout(1200);await page.screenshot({path:path.join(qa,'10-pic-signal-paths.png')});
 await page.evaluate(()=>NPO.select('monitor_pd'));assert.equal((await state()).signalPath,'cw');await page.locator('[data-focus="monitor_pd"]').click();
 await page.evaluate(()=>NPO.select('els'));await page.waitForTimeout(1000);await page.screenshot({path:path.join(qa,'11-els.png')});
 mark('Signal route controls, component-linked paths, PIC and ELS view rendering');
 await page.locator('[data-pricing="cost"]').click();await page.locator('[data-tab="bom"]').click();await page.locator('#baseline').click();
 assert.equal((await state()).config.pricingMode,'allocation');assert.equal((await state()).total,650,'100G reference action uses budget mode');
 await page.locator('[data-tab="structure"]').click();await page.locator('[data-lane="200"]').click();await setting('cwFanout',4);
 mark('Reference-structure action restores the budget model');
 await page.locator('#home-view').click();await setting('rotators',1);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);await page.screenshot({path:path.join(qa,'12-mobile-updated.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'No horizontal page overflow on mobile');
 await page.locator('[data-pricing="cost"]').click();await page.locator('#compare-config').click();
 assert(await page.locator('#detail-dialog').isVisible());assert(await page.evaluate(()=>{const r=document.querySelector('#detail-dialog').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth}));
 mark('Mobile pricing controls and comparison dialog');
 assert.equal(loadedArtifactHash,crypto.createHash('sha256').update(fs.readFileSync(artifact)).digest('hex'),'Artifact must remain unchanged during QA');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(qa,'ui-results.json'),JSON.stringify({passed:true,checks,errors,artifactSha256:crypto.createHash('sha256').update(fs.readFileSync(artifact)).digest('hex')},null,2));
 console.log(JSON.stringify({passed:true,checks}));
})().catch(async e=>{if(page)await page.screenshot({path:path.join(qa,'ui-error.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
