// Shared taxonomy. Quantities are per selected NPO optical unit, including allocated light source.
const n=(id,parent,name,en,category,unit,role,detail,qtyRule)=>({id,parent,name,en,category,unit,role,detail,qtyRule});
export const catalog=[
n('npo',null,'NPO光互连单元','Near-Packaged Optics','系统','套','将高速电信号转换为光信号，并接收光信号','边界为一套所选带宽的光引擎、连接封装及分摊光源。旁边的交换ASIC不属于本组件树或BOM。','one'),
n('engine','npo','光引擎','Optical Engine','光电组件','组','完成电光转换与光电转换','由PIC、发射驱动及接收放大链组成；光引擎可包含多颗PIC。示意布局不代表某一厂商封装。','one'),
n('pic','engine','硅光PIC','Photonic Integrated Circuit','光子芯片','颗','集成调制、探测和片上光路','用每颗PIC承载的光通道数计算颗数；实际划分取决于芯片设计与良率。','pic'),
n('modulator','pic','调制器','Optical Modulator','片上有源光学','路','把电信号编码到连续光上','示意采用MZM结构；微环等实现是其他路线。调制器计入PIC，不应再次叠加芯片采购价值。','lanes'),
n('photodiode','pic','光探测器','Photodiode','片上有源光学','路','将接收光转换为电流信号','示意为接收端探测结构，与TIA配合。独立探测芯片与PIC集成方案的物料边界不同。','lanes'),
n('waveguide','pic','波导','Waveguide','片上无源光学','组','约束并传导片上光','波导长度与拓扑属于版图参数，页面不把波导段当成独立采购件。','pic'),
n('coupler','pic','光耦合结构','Edge / Grating Coupler','片上无源光学','组','连接片上波导与光纤接口','边缘耦合与光栅耦合为替代实现；图中展示一般接口位置。','pic'),
n('splitter','pic','分光器','Optical Splitter','片上无源光学','组','把光源功率分配到调制通道','具体分光比受激光功率、插损与链路预算约束。','pic'),
n('phase','pic','相位与温度调节','Phase / Thermal Tuning','片上控制结构','组','校准光路工作点','加热器与监控结构通常随PIC集成，数量不等于外部芯片颗数。','pic'),
n('eic','engine','EIC · Driver＋TIA','Tx / Rx Electronics','有源电芯片组','组','提供发射驱动和接收放大','公开资料仅披露Driver与TIA合计。页面按显式工程权重拆分；点击价格可查看公式，不能将分配值视为独立报价。','one'),
n('driver','eic','Driver','Modulator Driver','有源电芯片','颗','驱动发射调制器','功能通道数等于Tx通道数；封装颗数按每颗集成通道数向上取整。','driver'),
n('tia','eic','TIA','Transimpedance Amplifier','有源电芯片','颗','放大接收探测器的微弱电流','功能通道数等于Rx通道数；四通道与八通道封装会改变颗数，不改变总接收通道数。','tia'),
n('fau','engine','Fiber Array','Fiber Array Unit','无源光学组件','组','将一排光纤精密定位到光引擎','Tx与Rx分体排纤的示意模型。每组纤芯容量可调整，光纤根数与FAU组件数分别统计。','fau'),
n('vgroove','fau','V槽基板','V-groove Substrate','精密结构件','片','固定光纤中心距和排列精度','常见玻璃或硅基板；本页每FAU一片为装配假设。','fau'),
n('fiber','fau','信号光纤','Signal Fiber','无源光学','根','传输Tx与Rx光信号','当前为并行单波长光链路，信号光纤根数为Tx＋Rx。WDM复用不在当前数量模型内。','fibers'),
n('lens','fau','微透镜阵列','Microlens Array','无源光学','组','整形与耦合阵列光束','仅在所选透镜耦合结构中需要；直接耦合FAU可在高级参数关闭。','fauLens'),
n('adhesive','fau','光学胶与固定','Optical Adhesive','封装材料','组','保持光纤与基板的装配位置','胶量与工艺良率不适合直接按每根光纤报价，计为组件中的工艺材料。','fau'),
n('els','npo','光源组件','Laser Source Assembly','光源子系统','套','为光引擎提供连续光','外置方式可多光引擎共享一套ELS；左侧同时显示物理套数及本NPO分摊比例。板载光源是另一封装情景。','els'),
n('cw','els','CW激光器','CW Laser','有源光学器件','路','产生供调制器使用的连续光','激光路数按光通道与供光扇出计算。供光能力不只取决于数量，还取决于功率和损耗。','cw'),
n('laser_die','cw','InP激光芯片','InP Laser Die','半导体芯片','颗','通过受激辐射产生激光','数量采用每光源路一颗芯片的示意假设；多发射腔或阵列产品需要另行建模。','cw'),
n('laser_submount','cw','热沉与Submount','Laser Submount','封装结构件','片','为激光芯片提供安装及导热路径','材料和尺寸依功率、封装及散热方案变化。','cw'),
n('isolator','els','光隔离器','Optical Isolator','无源光学组件','只','抑制反射光返回激光器','示意为每CW路一个单级隔离器，实际可采用集成或不同级数方案；不是所有NPO架构的通用颗数。','isolator'),
n('faraday','isolator','法拉第旋片','Faraday Rotator','磁光元件','片','在磁场作用下旋转偏振方向','与偏振元件配合实现隔离。当前按单级隔离器一片建模，可调整每隔离器片数。','faraday'),
n('garnet','faraday','磁光晶体材料','Magneto-optic Garnet','功能材料','份','提供非互易磁光响应','薄膜晶体的材料体系、波段与生长工艺不同；原料与加工旋片属于不同价值层。','faraday'),
n('coating','faraday','光学镀膜','Anti-reflection Coating','表面工艺','组','降低工作波段表面反射','镀膜是旋片加工的一部分；没有独立成本资料时只标示包含关系。','faraday'),
n('polarizer','isolator','起偏元件','Polarizer','无源光学','片','建立输入偏振方向','偏振相关型隔离器的示意结构。其他偏振无关型产品可能采用双折射晶体等不同结构。','isolator'),
n('analyzer','isolator','检偏元件','Analyzer','无源光学','片','与旋转后的偏振方向配合','与起偏元件及法拉第旋片共同构成隔离光路。','isolator'),
n('magnet','isolator','永久磁体','Permanent Magnet','磁性材料','组','为磁光元件提供工作磁场','具体磁路与元件设计相关，示意为一个磁体组件。','isolator'),
n('collimator','isolator','准直透镜','Collimating Lens','无源光学','片','将光纤出射光准直并重新耦合','每只隔离器两片是本示意的封装假设，芯片级或自由空间方案可能不同。','collimator'),
n('isolator_housing','isolator','隔离器壳体','Isolator Housing','精密结构件','套','固定内部光学件并保护装配','整体隔离器采购价值已经包括内部装配及封装。','isolator'),
n('pm_fiber','els','保偏供光纤','Polarization-maintaining Fiber','无源光学','根','输送并保持供光偏振','供光纤与信号FAU的Tx/Rx光纤单独计数。','cw'),
n('laser_driver','els','激光电流驱动','Laser Current Driver','有源电芯片','组','为CW激光器提供稳定偏置电流','与高速调制Driver功能不同，数量采用每路供光一组驱动功能。','cw'),
n('monitor_pd','els','监控探测器','Monitor Photodiode','有源光学','路','反馈光源输出功率','可内置于激光封装，不应默认视为独立采购芯片。','cw'),
n('tec','els','温控组件','TEC / Temperature Control','热电器件','组','稳定光源温度与工作点','TEC温控与陶瓷壳体只有组合参考区间。当前拆分值使用明确工程假设，点击价格查看分配过程。','els'),
n('substrate','engine','基板与电连接','Substrate & Electrical Interconnect','封装组件','套','支撑光电芯片并完成高速电连接','不同NPO结构可能使用有机基板、中介层或不同PCB工艺，不把这些技术全部当成必选叠加。','one'),
n('pcb','substrate','高密度电路板','HDI / mSAP PCB','电互连','片','连接光引擎、电源与系统接口','mSAP为参考材料模型中的组合项；并非所有厂商必然采用相同工艺。','one'),
n('interposer','substrate','中介层与精密载板','Interposer / Carrier','先进封装','组','提供芯片间短距离互连','在高级参数启用；未启用时仍可浏览器件知识，但数量与BOM不计入。','interposer'),
n('other','engine','配套与热管理','Supporting Materials','配套组件','套','提供控制、连接、机械与散热支持','参考BOM仅披露其他材料组合预算。内部组件按明确工程权重分配，子件不再叠加到总额。','one'),
n('connector','other','光电连接器','Optical / Electrical Connector','连接组件','组','与外部电接口和光纤系统连接','组件数量按所选NPO单元一组接口集合表示，不能从带宽直接反推具体插头数。','one'),
n('control','other','控制与供电','Control & Power','电子组件','套','管理供电、监控和校准','没有来源的细分成本并入其他材料，避免加总出重复成本。','one'),
n('mcu','control','控制芯片','MCU / Controller','有源电芯片','组','执行状态管理和校准','每NPO一组是功能分组，实际可由系统级控制器共享。','one'),
n('pmic','control','电源管理','PMIC / DC-DC','有源电芯片','组','提供多路稳定电源','数量为电源功能组，不等于已核定的独立芯片数。','one'),
n('thermal','other','散热与机械封装','Thermal & Mechanical','封装组件','套','提供散热路径及机械保护','可视化展示功能层级，详细热设计仍需要功耗与环境条件。','one'),
n('heatsink','thermal','散热器','Heat Spreader / Sink','结构件','组','把芯片热量传向系统冷却侧','散热面积与功耗相关，不按光通道等比例确定外形。','one'),
n('tim','thermal','导热界面材料','Thermal Interface Material','材料','组','填充接触界面并降低热阻','在封装组合成本内，缺少拆分资料时不生成独立报价。','one'),
n('housing','thermal','封装外壳','Mechanical Housing','结构件','套','保护器件并保持装配精度','示意外形不代表某家产品的尺寸或实物拆解。','one')
];
